# Generated by Django 3.2.4 on 2021-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main',
            field=models.TextField(max_length=2500, null=True),
        ),
    ]
